---
# Указывает, нужно ли развертывать NGINX
nginx_install: true

# Указывает, нужно ли только обновить конфигурацию NGINX
nginx_config_only: false

# Порт HTTP-сервера
nginx_http_port: 80

# Порт HTTPS-сервера
nginx_https_port: 443

# Список серверных имен (FQDN) для виртуальных хостов
nginx_server_names:
  - www.example.com
  - example.com

# Путь к файлу конфигурации NGINX
nginx_config_path: /etc/nginx/conf.d/default.conf

# Путь к шаблону конфигурации NGINX
nginx_template_path: /templates/nginx.conf.j2

# Путь к папке с логами NGINX
nginx_log_path: /var/log/nginx

# Путь к папке с данными NGINX
nginx_data_path: /var/lib/nginx

# Образ Docker для NGINX
nginx_docker_image: nginx

# Тег Docker для NGINX
nginx_docker_tag: latest

# Тома Docker для NGINX
nginx_docker_volumes:
  - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
  - /var/log/nginx:/var/log/nginx
  - /var/lib/nginx:/var/lib/nginx

# Порты Docker для NGINX
nginx_docker_ports:
  - "80:80"
  - "443:443"

# Переменные среды Docker для NGINX
nginx_docker_env:
  - TZ=${TIMEZONE}

# Дополнительные параметры Docker
nginx_docker_extra_args: []